### DISCUSSION TITLE
Problems using wordpress integration with elementor

### DISCUSSION THREAD

**Discussion by floek** [mosparo/mosparo#186] [Problems & Issues] [answered]
Hi,

I'm using wordpress / elementor with the mosparo wordpress plugin. I have a simple Elementor "Form Field" with the mosparo input added. The mosparo box is shown, but when I fill my form and click on the mosparo button, elementor shows an error the check failed.

I can see three post requests:

1. mosapro endpoint / `check-form-data`: response `valid: true`
2. wordpress / `admin-ajax.php`: response `success: false`
3. mosapro endpoint / `request-submit-token`: response `submitToken: ...`

Maybe the request in the middle to wordpress / `admin-ajax.php` causes the problem, but I don't know why.

Any success stories with this setup? Is there a debug log, where I can check why it failes? The webserver logs etc. are clean.

Thank you for help.

Best,
floek

**Comment by zepich** [comment]
Hi @floek 

Thank you very much for your question.

Do you see the submission in mosparo in the project?

Do you see the request to `/api/v1/verification` in the access log of your mosparo installation (in the access log file from your web server)?

If you see the request in the access log, can you check if you see any errors in the mosparo log file? You can find that in the mosparo directory in `var/log`, and the log file is called `prod-{date}.log`.

Do you have a valid SSL certificate for your mosparo installation, or do you use a self-signed certificate?

Kind regards,

zepich

**Reply by floek** [reply]
Hi @zepich,

- No submission in mosparo (and in elementor)
- No request to `/api/v1/verification` in mosparo access log
- SSL: letsencrypt staging, but verification is turned off in mosparo wordpress plugin.

Thank your for helping me.

Best,
floek

**Reply by zepich** [reply]
Hi @floek 

Thank you for your response. Very interesting...

Have you set up any other protection method in your form, like reCAPTCHA or Honeypot?

Do you see an error message or additional data in the `admin-ajax.php` request or only `success: false`?

Are you using the latest version of Elementor? (Elementor and Elementor Pro version 3.19.2)

Thank you very much for your information.

Kind regards,

zepich

**Reply by floek** [reply]
Hi @zepich,

no other protection method. admin-ajax.php says:
```json
{
    "success": false,
    "data": {
        "message": "Die \u00dcbermittlung der E-Mail ist aufgrund eines Serverfehlers fehlgeschlagen.",
        "errors": {
            "field_64dd817": "Die \u00dcberpr\u00fcfung ist fehlgeschlagen, was bedeutet, dass das Formular Spam enth\u00e4lt.",
            "": ""
        },
        "data": []
    }
}
```

Another point: I cannot login to wordpress anymore, when mosaparo is active. Error is similar:
```
 Ein genereller Fehler ist aufgetreten: An error occurred while sending the request to mosparo. 
```

So it may be a general problem with the connection wordpress / mosparo. I'v some general questions here: I'm using docker compose to run wordpress, mysql and mosparo. The webservices are proxied by a external nginx. 

Initially my approach was to use the docker-compose internal service name in the mosparo wordpress configuration to connect to mosparo, but this did not work, because a javascript file is loaded from the external mosparo url. So I've used the external url now.

Any ideas? suggestions?

Best,
floek

**Reply by zepich** [reply]
Hi @floek 

Thank you very much for the details. I guess it's an issue in combination with Docker.

Can you share your docker-compose file so I can test it with the same setup as you have?

Thank you very much

Kind regards,

zepich

**Reply by floek** [reply]
Sure:
```yaml
version: "3.4"
services:
  mariadb:
    image: docker.io/bitnami/mariadb
    restart: always
    ports:
      - '127.0.0.1:3306:3306'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      - MARIADB_ROOT_PASSWORD=wordpress
      - MARIADB_USER=wordpress
      - MARIADB_PASSWORD=wordpress
      - MARIADB_DATABASE=wordpress
    networks:
      - wordpress
  wordpress:
    image: docker.io/bitnami/wordpress:6.4.3
    restart: always
    ports:
      - '127.0.0.1:8090:8080'
    volumes:
      - './wordpress:/bitnami/wordpress'
    environment:
      - WORDPRESS_DATABASE_NAME=wordpress
      - WORDPRESS_DATABASE_USER=wordpress
      - WORDPRESS_DATABASE_PASSWORD=wordpress
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_SKIP_BOOTSTRAP=yes
      - WORDPRESS_HTACCESS_OVERRIDE_NONE=yes
      - WORDPRESS_SCHEME=http
      - WORDPRESS_ENABLE_HTACCESS_PERSISTENCE=no
      - WORDPRESS_MULTISITE_FILEUPLOAD_MAXK=6629145
      - PHP_UPLOAD_MAX_FILESIZE=6629145k
    depends_on:
      - mariadb
    networks:
      - wordpress
  mosparo_web:
    image: mosparo/mosparo:latest
    ports:
      - '127.0.0.1:8091:80'
    restart: always
    environment:
      - MOSPARO_ENABLE_WEBSERVER=1
      - MOSPARO_ENABLE_CRON=0
    volumes:
      - mosparo_data:/mosparo-data
    networks:
      - wordpress
  mosparo_cron:
    image: mosparo/mosparo:latest
    restart: always
    environment:
      - MOSPARO_ENABLE_WEBSERVER=0
      - MOSPARO_ENABLE_CRON=1
    volumes:
      - mosparo_data:/mosparo-data
    networks:
      - wordpress
volumes:
  mariadb_data:
  mosparo_data:
networks:
  wordpress:
```
