### ISSUE TITLE
Docker Compose documentation doesn't include proper setup instructions for database

### ISSUE THREAD

**Issue by ThatOneCalculator** [mosparo/mosparo#127]
Currently, I'm using an unmodified version of the docker-compose.yml file. However, I can't get past this step in the setup:

>  It was not possible to connect to the database. Please check your settings below and try again. 

![image](https://github.com/mosparo/mosparo/assets/44733677/1e6d8e1b-c27d-498d-9eee-c85f64cc0110)

**Comment by zepich** [comment]
Hi @ThatOneCalculator 

Thank you very much for your message.

Please try `mysql` as the database host instead of `127.0.0.1`. It should work with that and the unmodified version of the docker-compose file.

Let me know if that works or if you still have the issue.

Kind regards,

zepich

**Comment by ThatOneCalculator** [comment]
Thank you for the quick reply. Unfortunately, that still didn't work. For reference, here's the version I'm using (it's from the documentation, all I changed was the web port):

```
services:
  db:
    # We recommend the mariadb image
    image: mariadb:10.10
    # If you want to use MySQL, uncomment the following line (and comment the one above)
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mosparo_root_pw
      - MYSQL_DATABASE=mosparo
      - MYSQL_USER=mosparo
      - MYSQL_PASSWORD=mosparo_password
    expose:
      - 3306
      - 33060
  mosparo_web:
    image: mosparo/mosparo:latest
    ports:
      - 127.0.0.1:3100:80
    restart: always
    environment:
      - MOSPARO_ENABLE_WEBSERVER=1
      - MOSPARO_ENABLE_CRON=0
    volumes:
      - mosparo_data:/mosparo-data
  mosparo_cron:
    image: mosparo/mosparo:latest
    restart: always
    environment:
      - MOSPARO_ENABLE_WEBSERVER=0
      - MOSPARO_ENABLE_CRON=1
    volumes:
      - mosparo_data:/mosparo-data
volumes:
  db_data:
  mosparo_data:
```

**Comment by zepich** [comment]
Hi @ThatOneCalculator 

Ah, I'm very sorry!

Please use `db` instead of `127.0.0.1` as database host.

(I tested last week with a MySQL container with the name `mysql` why I had it wrong in my mind)

I hope that helps!

Additionally, I saw that we do not mention that in the documentation. I will fix the documentation.

Kind regards,

zepich

**Comment by ThatOneCalculator** [comment]
That did the trick! Thank you so much.

**Comment by zepich** [comment]
You're welcome!

**Comment by zepich** [comment]
The documentation is updated.

**Comment by TheDogHusky** [comment]
Hello!

I came across the same issue, but putting db as the host doesn't fix the issue.

**Comment by TheDogHusky** [comment]
Here is a screenshot, and my docker-compose:
https://safe.classydev.fr/firefox_el_Am_Zrt9rv-OtFZBlOLD5J7vHw5Nhbi8ta252RTD5yf.png

```yml
services:
  db:
    # We recommend the mariadb image
    image: mariadb:10.10
    # If you want to use MySQL, uncomment the following line (and comment the one above)
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=<hidden>
      - MYSQL_DATABASE=mosparo
      - MYSQL_USER=mosparo
      - MYSQL_PASSWORD=<hidden>
    expose:
      - 3306
      - 33060
  mosparo_web:
    image: mosparo/mosparo:latest
    ports:
      - 127.0.0.1:8085:80
    restart: always
    environment:
      - MOSPARO_ENABLE_WEBSERVER=1
      - MOSPARO_ENABLE_CRON=0
    volumes:
      - mosparo_data:/mosparo-data
  mosparo_cron:
    image: mosparo/mosparo:latest
    restart: always
    environment:
      - MOSPARO_ENABLE_WEBSERVER=0
      - MOSPARO_ENABLE_CRON=1
    volumes:
      - mosparo_data:/mosparo-data
volumes:
  db_data:
  mosparo_data:
  ```
