### ISSUE TITLE
Error 500 on submit login

### ISSUE THREAD

**Issue by ghpaini** [mosparo/mosparo#257]
Hello, I’m encountering some issues after the wizard configuration.

I used docker-compose and followed the steps in the [documentation](https://documentation.mosparo.io/docs/installation/install/docker).

I received a 500 error after submitting the login form and was able to retrieve this error log from the container volumes.

`[2024-07-06T12:07:30.785418+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Filesystem\Exception\IOException: "Cannot rename "/tmp/url_matching_routes.phpgv5MnI" to "/mosparo-data/var/cache/prod/url_matching_routes.php": rename(/tmp/url_matching_routes.phpgv5MnI,/mosparo-data/var/cache/prod/url_matching_routes.php): Permission denied" at Filesystem.php line 312 {"exception":"[object] (Symfony\\Component\\Filesystem\\Exception\\IOException(code: 0): Cannot rename \"/tmp/url_matching_routes.phpgv5MnI\" to \"/mosparo-data/var/cache/prod/url_matching_routes.php\": rename(/tmp/url_matching_routes.phpgv5MnI,/mosparo-data/var/cache/prod/url_matching_routes.php): Permission denied at /mosparo/vendor/symfony/filesystem/Filesystem.php:312)"} []
`

**Comment by zepich** [comment]
Hi @ghpaini 

Thank you very much for your issue.

The error message generally means that mosparo inside the Docker image cannot write to the Docker volume.

If you used the provided docker-compose.yml file, it should be no problem at all. But can you verify that the volume exists correctly? You can use `docker volume ls` to list all volumes and `docker volume inspect <name>` to see all the volume details.

Additionally, you can use `docker exec -it 'mosparo-docker-mosparo_web-1' /bin/bash` (adjust the name `mosparo-docker-mosparo_web-1` of the Docker container if needed) to get a shell inside the Docker container. You can use `ls -la /mosparo-data/var/cache/` in the container. What's the result of this command?

Kind regards,

zepich

**Comment by ghpaini** [comment]
Hi @zepich 

Thank you for the support 😄.

I was only able to get the error log through the mosparo_db_data volume, see the results of `docker volume ls`:

`DRIVER    VOLUME NAME`
`local     mosparo_db_data`
`local     mosparo_mosparo_data`

And this is the result of  `ls -la /mosparo-data/var/cache/`:

`drwxr-xr-x 3 www-data www-data 4096 Jul  6 14:04 .`
`drwxr-xr-x 4 www-data www-data 4096 Jul  5 20:33 ..`
`drwxr-xr-x 8 www-data www-data 4096 Jul  6 14:04 prod`

**Comment by zepich** [comment]
Hi @ghpaini 

Thank you for the outputs.

Have you tried to log in only once or multiple times with the same error?

Do you have enough free space on your server?

I can see that the cache directory was created. I guess it was when you installed mosparo. So technically, there should be no reason for the login not working.

Kind regards,

zepich

**Comment by ghpaini** [comment]
I've tried only a couple of times.

I’m running MOSPARO on my machine, only to try out the application.

The cache directory was created when I first opened the localhost:8080 on my browser.

I’ll wait until Monday to try and run Mosparo on another machine with more free space (I have about 20 GBs), but I don’t think that’s the cause of my issue here.

If it’s worth mentioning, I am running the images on my Windows computer.

I cleaned everything (images, containers and volumes) and tried to run again, but got the same 500 error after login. Although
this time the error was SSL related:

`
[2024-07-06T16:42:14.874336+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\HttpClient\Exception\TransportException: "SSL certificate problem: self-signed certificate in certificate chain for "https://updates.mosparo.io/v/1.2.json"." at ErrorChunk.php line 56 {"exception":"[object] (Symfony\\Component\\HttpClient\\Exception\\TransportException(code: 0): SSL certificate problem: self-signed certificate in certificate chain for \"https://updates.mosparo.io/v/1.2.json\". at /mosparo/vendor/symfony/http-client/Chunk/ErrorChunk.php:56)\n[previous exception] [object] (Symfony\\Component\\HttpClient\\Exception\\TransportException(code: 0): SSL certificate problem: self-signed certificate in certificate chain for \"https://updates.mosparo.io/v/1.2.json\". at /mosparo/vendor/symfony/http-client/Response/CurlResponse.php:315)"} []
`

**Comment by zepich** [comment]
Hi @ghpaini 

Thank you very much for your answer and the details.

No, if you have 20 GB of free space, that should be way more than enough, so that's not the problem (but sometimes, no space left creates very interesting issues, so I wanted to make sure that that's not the problem in your case).

Thank you very much for the information about Windows. I've just tested it on a Windows machine. I installed Docker Desktop (with WSL), restarted the machine, and used the Docker compose file we provided in our documentation to create the containers. Everything worked without any problem.

Are any files inside the `var/cache/prod` directory?

Regarding the SSL issue: Do you use any tool to block outgoing communication (Antivirus/Firewall)? Can you test with `ping updates.mosparo.io` to which IP address it resolves? There should be no such error since we're using valid certificates.

Kind regards,

zepich

**Comment by ghpaini** [comment]
Hi @zepich 

There is some files in `var/cache/prod`:

`drwxr-xr-x   8 www-data www-data  4096 Jul  6 16:41 .`
`drwxr-xr-x   3 www-data www-data  4096 Jul  6 16:41 ..`
`drwxr-xr-x   2 www-data www-data 36864 Jul  6 16:41 Container1N2uDDh`
`-rw-r--r--   1 www-data www-data   875 Jul  6 16:41 Mosparo_KernelProdContainer.php`
`-rw-r--r--   1 www-data www-data     0 Jul  6 16:41 Mosparo_KernelProdContainer.php.lock`
`-rw-r--r--   1 www-data www-data 90643 Jul  6 16:41 Mosparo_KernelProdContainer.php.meta`
`-rw-r--r--   1 www-data www-data 61907 Jul  6 16:41 Mosparo_KernelProdContainer.preload.php`
`drwxr-xr-x   3 www-data www-data  4096 Jul  6 16:41 Symfony`
`-rw-r--r--   1 www-data www-data    98 Jul  6 16:41 annotations.map`
`drwxr-xr-x   3 www-data www-data  4096 Jul  6 16:41 doctrine`
`drwxr-xr-x   4 www-data www-data  4096 Jul  6 16:41 pools`
`-rw-r--r--   1 www-data www-data   100 Jul  6 16:41 serialization.php`
`drwxr-xr-x   2 www-data www-data 12288 Jul  6 16:41 translations`
`drwxr-xr-x 110 www-data www-data  4096 Jul  6 16:41 twig`
`-rw-r--r--   1 www-data www-data 40024 Jul  6 16:41 url_generating_routes.php`
`-rw-r--r--   1 www-data www-data  9346 Jul  6 16:41 url_generating_routes.php.meta`
`-rw-r--r--   1 www-data www-data 25491 Jul  6 16:41 url_matching_routes.php`
`-rw-r--r--   1 www-data www-data  9346 Jul  6 16:41 url_matching_routes.php.meta`
`-rw-r--r--   1 www-data www-data  5968 Jul  6 16:41 validation.php`
`-rw-r--r--   1 www-data www-data   745 Jul  6 16:41 webpack_encore.cache.php`.

The resolution for updates.mosparo.io was mosparo.io [216.238.102.197], but the ping received no response.

Is it mandatory to have access to mosparo.io domains? Because, I really don’t think I can change anything in the firewall of my computer here. I’ll give it a try in another Windows environment that I have, to validate if it’s some kind of Firewall or Antivirus block.

I forgot to mention some changes that I have made to the configuration files. My Web container wasn’t showing any errors at all. It was only some “display_error” flags that might explain why I am not getting the first error anymore.

**Comment by zepich** [comment]
Hi @ghpaini 

Thank you very much for your response.

No, there is no need to have access to the mosparo.io domains. You can turn off the automatic update check by setting the following environment variable:

`MOSPARO_AUTOMATIC_UPDATE_CHECK_ENABLED=0`

You have to add it to the Docker compose file like this:

```yaml
services:
  db:
    # We recommend the mariadb image
    image: mariadb:10.10
    # If you want to use MySQL, uncomment the following line (and comment the one above)
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mosparo_root_pw
      - MYSQL_DATABASE=mosparo
      - MYSQL_USER=mosparo
      - MYSQL_PASSWORD=mosparo_password
    expose:
      - 3306
      - 33060
  mosparo_web:
    image: mosparo/mosparo:latest
    ports:
      - 127.0.0.1:8080:80
    restart: always
    environment:
      - MOSPARO_ENABLE_WEBSERVER=1
      - MOSPARO_ENABLE_CRON=0
      - MOSPARO_AUTOMATIC_UPDATE_CHECK_ENABLED=0  # Disable update check
    volumes:
      - mosparo_data:/mosparo-data
  mosparo_cron:
    image: mosparo/mosparo:latest
    restart: always
    environment:
      - MOSPARO_ENABLE_WEBSERVER=0
      - MOSPARO_ENABLE_CRON=1
      - MOSPARO_AUTOMATIC_UPDATE_CHECK_ENABLED=0  # Disable update check
    volumes:
      - mosparo_data:/mosparo-data
volumes:
  db_data:
  mosparo_data:
```

I will check that one server, but generally, it should not return wrong SSL certificate.

Can you check with this Docker compose file if you still have the first error?

Kind regards,

zepich
