### ISSUE TITLE
App not available after upgrading to 1.3.0

### ISSUE THREAD

**Issue by mad73923** [mosparo/mosparo#302]
I'm running mosparo on a ARM machine with the following docker compose:

```
services:
  db:
    container_name: captcha_db
    # We recommend the mariadb image
    image: mariadb:11.4
    # If you want to use MySQL, uncomment the following line (and comment the one above)
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=mosparo
      - MYSQL_USER=mosparo
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - captcha

  mosparo_web:
    depends_on:
      - db
    container_name: captcha_web
    image: mosparo/mosparo:latest
    restart: unless-stopped
    environment:
      - MOSPARO_ENABLE_WEBSERVER=1
      - MOSPARO_ENABLE_CRON=0
    volumes:
      - mosparo_data:/mosparo-data
    networks:
      - traefikpub
      - captcha
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.[redacted]-captcha.entrypoints=web"
      - "traefik.http.routers.[redacted]-captcha.rule=Host(`captcha.[redacted].ch`)"
      - "traefik.http.middlewares.[redacted]-captcha-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.[redacted]-captcha.middlewares=[redacted]-captcha-https-redirect,[redacted]-captcha-ratelimit"
      - "traefik.http.middlewares.[redacted]-captcha-ratelimit.ratelimit.average=10"
      - "traefik.http.middlewares.[redacted]-captcha-ratelimit.ratelimit.burst=50"
      - "traefik.http.routers.[redacted]-captcha-secure.middlewares=secHeaders@file,[redacted]-captcha-ratelimit"
      - "traefik.http.routers.[redacted]-captcha-secure.entrypoints=websecure"
      - "traefik.http.routers.[redacted]-captcha-secure.rule=Host(`captcha.[redacted].ch`)"
      - "traefik.http.routers.[redacted]-captcha-secure.service=[redacted]-captcha"
      - "traefik.http.routers.[redacted]-captcha-secure.tls=true"
      - "traefik.http.routers.[redacted]-captcha-secure.tls.certresolver=myresolver"
      - "traefik.http.services.[redacted]-captcha.loadbalancer.server.port=80"

  mosparo_cron:
    depends_on:
      - db
    container_name: captcha_cron
    image: mosparo/mosparo:latest
    restart: unless-stopped
    environment:
      - MOSPARO_ENABLE_WEBSERVER=0
      - MOSPARO_ENABLE_CRON=1
    volumes:
      - mosparo_data:/mosparo-data
    networks:
      - captcha

volumes:
  db_data:
  mosparo_data:

networks:
  captcha:
  traefikpub:
    external: true
```

After upgrading to 1.3.0 I get a 404 when requesting the app.

Logs of all services:
```
captcha_db  | 2025-01-26 20:23:14+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:11.4.4+maria~ubu2404 started.
captcha_db  | 2025-01-26 20:23:15+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
captcha_db  | 2025-01-26 20:23:15+00:00 [Warn] [Entrypoint]: /sys/fs/cgroup///memory.pressure not writable, functionality unavailable to MariaDB
captcha_db  | 2025-01-26 20:23:15+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:11.4.4+maria~ubu2404 started.
captcha_db  | 2025-01-26 20:23:15+00:00 [Note] [Entrypoint]: MariaDB upgrade not required
captcha_db  | 2025-01-26 20:23:15 0 [Note] Starting MariaDB 11.4.4-MariaDB-ubu2404 source revision e9a502df08bad16aa8a354e854f3c014b1380e32 server_uid I8/zqvbJN3VHwCOp+HNWk+OqH0E= as process 1
captcha_db  | 2025-01-26 20:23:15 0 [Note] InnoDB: Compressed tables use zlib 1.3
captcha_db  | 2025-01-26 20:23:15 0 [Note] InnoDB: Number of transaction pools: 1    
captcha_db  | 2025-01-26 20:23:15 0 [Note] InnoDB: Using ARMv8 crc32 + pmull instructions
captcha_db  | 2025-01-26 20:23:15 0 [Note] mariadbd: O_TMPFILE is not supported on /tmp (disabling future attempts)
captcha_db  | 2025-01-26 20:23:15 0 [Note] InnoDB: Initializing buffer pool, total size = 128.000MiB, chunk size = 2.000MiB
captcha_db  | 2025-01-26 20:23:15 0 [Note] InnoDB: Completed initialization of buffer pool
captcha_db  | 2025-01-26 20:23:15 0 [Note] InnoDB: File system buffers for log disabled (block size=512 bytes)
captcha_db  | 2025-01-26 20:23:15 0 [Note] InnoDB: End of log at LSN=4451140
captcha_db  | 2025-01-26 20:23:15 0 [Note] InnoDB: Opened 3 undo tablespaces
captcha_db  | 2025-01-26 20:23:15 0 [Note] InnoDB: 128 rollback segments in 3 undo tablespaces are active.
captcha_db  | 2025-01-26 20:23:15 0 [Note] InnoDB: Setting file './ibtmp1' size to 12.000MiB. Physically writing the file full; Please wait ...
captcha_db  | 2025-01-26 20:23:15 0 [Note] InnoDB: File './ibtmp1' size is now 12.000MiB.
captcha_db  | 2025-01-26 20:23:15 0 [Note] InnoDB: log sequence number 4451140; transaction id 6442
captcha_db  | 2025-01-26 20:23:15 0 [Note] Plugin 'FEEDBACK' is disabled.
captcha_db  | 2025-01-26 20:23:15 0 [Note] Plugin 'wsrep-provider' is disabled.
captcha_db  | 2025-01-26 20:23:15 0 [Warning] 'default-authentication-plugin' is MySQL 5.6 / 5.7 compatible option. To be implemented in later versions.
captcha_db  | 2025-01-26 20:23:15 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
captcha_db  | 2025-01-26 20:23:15 0 [Note] InnoDB: Buffer pool(s) load completed at 250126 20:23:15
captcha_db  | 2025-01-26 20:23:17 0 [Note] Server socket created on IP: '0.0.0.0'.
captcha_db  | 2025-01-26 20:23:17 0 [Note] Server socket created on IP: '::'.
captcha_db  | 2025-01-26 20:23:17 0 [Note] mariadbd: Event Scheduler: Loaded 0 events
captcha_db  | 2025-01-26 20:23:17 0 [Note] mariadbd: ready for connections.
captcha_db  | Version: '11.4.4-MariaDB-ubu2404'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
captcha_web  | + set -o history -o histexpand
captcha_web  | + '[' -d /mosparo/var ']'
captcha_web  | + rm -rf /mosparo/var
captcha_web  | + '[' -d /mosparo-data/resources ']'
captcha_web  | + '[' -d /mosparo-data/var ']'
captcha_web  | + '[' -f /mosparo-data/env.mosparo.php ']'
captcha_web  | + chown -R www-data: /mosparo-data/
captcha_web  | + '[' -L /mosparo/public/resources ']'
captcha_web  | + ln -s /mosparo-data/resources/ /mosparo/public/resources
captcha_web  | + '[' -L /mosparo/var ']'
captcha_web  | + ln -s /mosparo-data/var/ /mosparo/var
captcha_web  | + '[' -L /mosparo/config/env.mosparo.php ']'
captcha_web  | + ln -s /mosparo-data/env.mosparo.php /mosparo/config/env.mosparo.php
captcha_web  | + rm -rf /mosparo-data/var/cache/prod
captcha_web  | + '[' 0 -eq 1 ']'
captcha_web  | + '[' 1 -eq 1 ']'
captcha_web  | + php-fpm -D -R
captcha_web  | [26-Jan-2025 20:23:15] NOTICE: fpm is running, pid 13
captcha_web  | + nginx -g 'daemon off;'
captcha_web  | [26-Jan-2025 20:23:15] NOTICE: ready to handle connections
captcha_web   | 127.0.0.1 -  26/Jan/2025:20:24:15 +0000 "GET /index.php" 500
captcha_web   | 127.0.0.1 -  26/Jan/2025:20:25:16 +0000 "GET /index.php" 500
captcha_web   | 127.0.0.1 -  26/Jan/2025:20:26:16 +0000 "GET /index.php" 500
captcha_web   | 127.0.0.1 -  26/Jan/2025:20:27:16 +0000 "GET /index.php" 500
captcha_web   | 127.0.0.1 -  26/Jan/2025:20:28:16 +0000 "GET /index.php" 500
captcha_web   | 127.0.0.1 -  26/Jan/2025:20:29:16 +0000 "GET /index.php" 500
captcha_cron  | + set -o history -o histexpand
captcha_cron  | + '[' -d /mosparo/var ']'
captcha_cron  | + rm -rf /mosparo/var
captcha_cron  | + '[' -d /mosparo-data/resources ']'
captcha_cron  | + '[' -d /mosparo-data/var ']'
captcha_cron  | + '[' -f /mosparo-data/env.mosparo.php ']'
captcha_cron  | + chown -R www-data: /mosparo-data/
captcha_cron  | + '[' -L /mosparo/public/resources ']'
captcha_cron  | + ln -s /mosparo-data/resources/ /mosparo/public/resources
captcha_cron  | + '[' -L /mosparo/var ']'
captcha_cron  | + ln -s /mosparo-data/var/ /mosparo/var
captcha_cron  | + '[' -L /mosparo/config/env.mosparo.php ']'
captcha_cron  | + ln -s /mosparo-data/env.mosparo.php /mosparo/config/env.mosparo.php
captcha_cron  | + rm -rf /mosparo-data/var/cache/prod
captcha_cron  | + '[' 1 -eq 1 ']'
captcha_cron  | + '[' 0 -eq 1 ']'
captcha_cron  | + cron -f
```

**Comment by zepich** [comment]
Hi @mad73923 

Thank you very much for your issue.

I've just tested it with a Hetzner ARM server, and everything works correctly with your Docker Compose file (at least for a new installation; I've tested it without Traefik).

![Image](https://github.com/user-attachments/assets/83598c89-dd59-4803-b4eb-93433da6f2fa)

In your log output, I can see that there is an error 500 in mosparo:

```text
captcha_web   | 127.0.0.1 -  26/Jan/2025:20:24:15 +0000 "GET /index.php" 500
captcha_web   | 127.0.0.1 -  26/Jan/2025:20:25:16 +0000 "GET /index.php" 500
captcha_web   | 127.0.0.1 -  26/Jan/2025:20:26:16 +0000 "GET /index.php" 500
captcha_web   | 127.0.0.1 -  26/Jan/2025:20:27:16 +0000 "GET /index.php" 500
captcha_web   | 127.0.0.1 -  26/Jan/2025:20:28:16 +0000 "GET /index.php" 500
captcha_web   | 127.0.0.1 -  26/Jan/2025:20:29:16 +0000 "GET /index.php" 500
```

Can you open a shell inside the web container and check the log files for anything visible?

```bash
docker exec -it captcha_web /bin/bash
```

Log files (inside the container):

- `/var/log/nginx/project_error.log`
- `/mosparo/var/log/prod-[date].log`

Thank you very much for your feedback.

Kind regards,

zepich

**Comment by mad73923** [comment]
Hi @zepich 

unfortunately, there are no logs:

```
root@29aff422e3c7:/mosparo# cat /var/log/nginx/project_error.log
root@29aff422e3c7:/mosparo# ls /mosparo/var/log                
prod-2024-11-06.log  prod-2024-11-09.log  prod-2024-12-08.log  prod-2024-12-11.log  prod-2024-12-16.log  prod-2024-12-21.log  prod-2024-12-27.log  prod-2024-12-30.log  prod-2025-01-01.log  prod-2025-01-07.log
```

Last Log file contains:
```
root@29aff422e3c7:/mosparo# cat /mosparo/var/log/prod-2025-01-07.log 
[2025-01-07T17:40:24.913484+00:00] request.INFO: Matched route "frontend_api_request_submit_token". {"route":"frontend_api_request_submit_token","route_parameters":{"_route":"frontend_api_request_submit_token","_controller":"Mosparo\\Controller\\Api\\V1\\Frontend\\FrontendApiController::request"},"request_uri":"https://captcha.[redacted].ch/api/v1/frontend/request-submit-token","method":"POST"} []
[2025-01-07T17:40:24.924854+00:00] app.INFO: Start cleanup process (Max iterations: 10; Force: 0; Ignore exceptions: 1, Timeout: 1.5s) [] []
[2025-01-07T17:40:24.928206+00:00] app.INFO: Cleanup process completed after 0s. [] []
[2025-01-07T17:40:24.934617+00:00] deprecation.INFO: User Deprecated: Since nelmio/security-bundle 3.4.0: The "Nelmio\SecurityBundle\EventListener\XssProtectionListener" class is deprecated, use Content Security Policy without allowing "unsafe-inline" scripts instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Since nelmio/security-bundle 3.4.0: The \"Nelmio\\SecurityBundle\\EventListener\\XssProtectionListener\" class is deprecated, use Content Security Policy without allowing \"unsafe-inline\" scripts instead. at /mosparo/vendor/nelmio/security-bundle/src/EventListener/XssProtectionListener.php:35)"} []
[2025-01-07T17:40:24.934657+00:00] deprecation.INFO: Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated {"exception":"[object] (ErrorException(code: 0): Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated at /mosparo/src/Subscriber/ApiSubscriber.php:88)"} []
[2025-01-07T17:40:24.934670+00:00] deprecation.INFO: Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated {"exception":"[object] (ErrorException(code: 0): Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated at /mosparo/src/Subscriber/ApiSubscriber.php:92)"} []
[2025-01-07T17:40:24.938966+00:00] request.CRITICAL: Uncaught PHP Exception TypeError: "Mosparo\Subscriber\ApiSubscriber::matchingOrigin(): Argument #2 ($originHost) must be of type string, null given, called in /mosparo/src/Subscriber/ApiSubscriber.php on line 106" at ApiSubscriber.php line 114 {"exception":"[object] (TypeError(code: 0): Mosparo\\Subscriber\\ApiSubscriber::matchingOrigin(): Argument #2 ($originHost) must be of type string, null given, called in /mosparo/src/Subscriber/ApiSubscriber.php on line 106 at /mosparo/src/Subscriber/ApiSubscriber.php:114)"} []
[2025-01-07T17:40:24.970351+00:00] deprecation.INFO: Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated {"exception":"[object] (ErrorException(code: 0): Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated at /mosparo/src/Subscriber/ApiSubscriber.php:88)"} []
[2025-01-07T17:40:24.970486+00:00] deprecation.INFO: Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated {"exception":"[object] (ErrorException(code: 0): Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated at /mosparo/src/Subscriber/ApiSubscriber.php:92)"} []

```

BR
Matthias

**Comment by zepich** [comment]
Hi @mad73923 / Matthias

Thank you very much for your response.

Can you go into the bash again and check the owner of `/mosparo-data/var/*`?

```bash
docker exec -it captcha_web /bin/bash
```

Is the owner of the folders and files set to `www-data`?

If not, please set it to `www-data`:

```
chown -R www-data: /mosparo-data/var/
```

Kind regards,

zepich / Matthias

**Comment by mad73923** [comment]
Hi @zepich 

the owner is `www-data`:
```
root@29aff422e3c7:/mosparo-data/var# ls -la
total 16
drwxr-xr-x 4 www-data www-data 4096 Jun 13  2024 .
drwxr-xr-x 4 www-data www-data 4096 Dec 23 14:55 ..
drwxr-xr-x 3 www-data www-data 4096 Jan 28 20:07 cache
drwxr-xr-x 2 www-data www-data 4096 Jan 29 01:15 log
```

BR
Matthias

**Comment by zepich** [comment]
Hi @mad73923 

Thank you very much for the output.

Can you show me the output of 

```bash
ls -la /mosparo
```

Thank you very much.

Kind regards,

zepich

**Comment by mad73923** [comment]
Hi @zepich 

seems like you're waiting for my answers... what a support!

```
root@29aff422e3c7:~# ls -la /mosparo
total 992
drwxr-xr-x  1 root root   4096 Jan 28 20:06 .
drwxr-xr-x  1 root root   4096 Jan 28 20:06 ..
-rw-rw-r--  1 root root   2153 Jan 21 08:25 .env
-rw-rw-r--  1 root root   3071 Jan 21 08:25 .env.local.dist
-rw-rw-r--  1 root root    317 Sep 29  2022 .env.test
-rw-rw-r--  1 root root    580 May 29  2024 .gitignore
-rw-rw-r--  1 root root    427 Apr  7  2024 .htaccess
-rw-rw-r--  1 root root      3 Apr 10  2023 .nvmrc
-rw-rw-r--  1 root root   5483 Sep 29  2022 CODE_OF_CONDUCT.md
-rw-rw-r--  1 root root    757 Jan 10  2023 CONTRIBUTING.md
-rw-rw-r--  1 root root   1108 Jan 21 08:25 LICENSE
-rw-rw-r--  1 root root   5713 Jan 21 08:25 README.md
-rw-rw-r--  1 root root    656 Nov 19  2023 SECURITY.md
drwxrwxr-x  6 root root   4096 Jan 21 08:25 assets
drwxrwxr-x  2 root root   4096 May 29  2024 bin
-rw-rw-r--  1 root root   4565 Jan 21 08:25 composer.json
-rw-rw-r--  1 root root 476977 Jan 21 08:25 composer.lock
drwxrwxr-x  1 root root   4096 Jan 28 20:06 config
drwxrwxr-x  4 root root   4096 Jan 21 08:25 docker
drwxrwxr-x  5 root root   4096 Jan 21 08:25 migrations
-rw-rw-r--  1 root root 382681 Jan 21 08:25 package-lock.json
-rw-rw-r--  1 root root   1341 Jan 21 08:25 package.json
-rw-rw-r--  1 root root   1195 May 29  2024 phpunit.xml.dist
drwxrwxr-x  1 root root   4096 Jan 28 20:06 public
drwxrwxr-x 21 root root   4096 Jan 21 08:25 src
-rw-rw-r--  1 root root  18748 Jun 16  2024 symfony.lock
drwxrwxr-x 14 root root   4096 Jan 21 08:25 templates
drwxrwxr-x  3 root root   4096 May 29  2024 tests
drwxrwxr-x  3 root root   4096 Jan 21 08:25 translations
lrwxrwxrwx  1 root root     18 Jan 28 20:06 var -> /mosparo-data/var/
drwxrwxr-x 40 root root   4096 Jan 21 08:25 vendor
-rw-rw-r--  1 root root   3665 May 29  2024 webpack.config.js
```

**Comment by zepich** [comment]
Hi @mad73923 

Thank you very much for your response.

> seems like you're waiting for my answers... what a support!

I don't like such mysterious problems... 

So, to summarize the problem:

1. You updated to the latest mosparo Docker image (v1.3.0)
2. You stopped the containers and started them again (after switching to the latest version)
3. You then tried to open mosparo in your browser
4. But everything you see is a 404 error

Is that correct so far?

5. In the Docker logs, we see that there is an error 500 happening
6. But we do not have an error message in the log files (we do not have any log files at all)

Can you set the ownership once to verify that that's not the problem?

```bash
chown -R www-data: /mosparo-data/var/cache/
chown -R www-data: /mosparo-data/var/log/
```

If that does not help, can you expose mosparo directly and check if that's working (since I tested it without Traefik)?

I did that by adding the port in the Docker Compose file:

```yaml
...
    networks:
      - traefikpub
      - captcha
    ports:
      - 8080:80
...
```

Kind regards,

zepich
