### ISSUE TITLE
Can't deploy Mosparo on Coolify

### ISSUE THREAD

**Issue by Benjaminpr** [mosparo/mosparo#326]
Hello!
I'm using Coolify (https://coolify.io/) to deploy most of my websites and side apps. I wanted to deploy Mosparo with it, which requires a docker-compose setup.
I tried to deploy the provided docker-compose file and modified it slightly to fit Coolify:
```yaml
services:
  db:
    image: 'mariadb:10.10'
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - 'db_data:/var/lib/mysql'
    restart: always
    networks:
      - mosparo_network
    environment:
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-mosparo}'
      - 'MYSQL_DATABASE=${MYSQL_DATABASE:-mosparo}'
      - 'MYSQL_USER=${MYSQL_USER:-mosparo}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD:-mosparo}'
  mosparo_web:
    image: 'mosparo/mosparo:latest'
    depends_on:
      - db
    ports:
      - '9090:80'
    restart: always
    networks:
      - mosparo_network
    environment:
      - MOSPARO_ENABLE_WEBSERVER=1
      - MOSPARO_ENABLE_CRON=0
      - MOSPARO_DB_HOST=db
      - MOSPARO_DB_PORT=3306
      - 'MOSPARO_DB_NAME=${MYSQL_DATABASE:-mosparo}'
      - 'MOSPARO_DB_USER=${MYSQL_USER:-mosparo}'
      - 'MOSPARO_DB_PASSWORD=${MYSQL_PASSWORD:-mosparo}'
    volumes:
      - 'mosparo_data:/mosparo-data'
  mosparo_cron:
    image: 'mosparo/mosparo:latest'
    depends_on:
      - db
    restart: always
    networks:
      - mosparo_network
    environment:
      - MOSPARO_ENABLE_WEBSERVER=0
      - MOSPARO_ENABLE_CRON=1
      - MOSPARO_DB_HOST=db
      - MOSPARO_DB_PORT=3306
      - 'MOSPARO_DB_NAME=${MYSQL_DATABASE:-mosparo}'
      - 'MOSPARO_DB_USER=${MYSQL_USER:-mosparo}'
      - 'MOSPARO_DB_PASSWORD=${MYSQL_PASSWORD:-mosparo}'
    volumes:
      - 'mosparo_data:/mosparo-data'
networks:
  mosparo_network: null
volumes:
  db_data: null
  mosparo_data: null

```
However, I'm experiencing two issues:

The containers are never considered "healthy" by Coolify until the Mosparo setup is completed. This could potentially be fixed by adding an autoinstall option in the docker image.
Sometimes the app crashes and becomes unreachable, making all captchas unusable.

I would like to help improve this integration, though I'm not sure if I have all the required skills. It would be really beneficial for Mosparo to be easily deployable on Coolify, as it's a great tool used by many people!
